---
title: "Homework 1: Using OLS Regression to Predict Median House Values in Philadelphia"
author: "Yiming Cao, Sujan Kakumanu, Angel Sanaa Rutherford"
date: October 15 2025
number-sections: true
format: pdf
---
```{r setup}
#| echo: false
#| results: "hide" # Hide the output
#| message: false  # Hide messages
#| warning: false  # Hide warnings
#| fig.show: "hide" # Hide plots/figures
options(scipen = 999)
install.packages("ggplot2")  
library(ggplot2)             
library(dplyr)
library(sf)
library(ggplot2)
library(patchwork)
library(MASS)
library(caret)
```

```{r exploratory-data-analysis}
#| echo: false
#| results: "hide" # Hide the output
#| message: false  # Hide messages
#| warning: false  # Hide warnings
#| fig.show: "hide" # Hide plots/figures
regression_data <- read.csv("./RegressionData.csv")

hist(regression_data$MEDHVAL)
hist(regression_data$PCTBACHMOR)
hist(regression_data$NBELPOV100)
hist(regression_data$PCTVACANT)
hist(regression_data$PCTSINGLES)

plot(regression_data$PCTBACHMOR, regression_data$MEDHVAL)
plot(regression_data$NBELPOV100, regression_data$MEDHVAL)
plot(regression_data$PCTVACANT, regression_data$MEDHVAL)
plot(regression_data$PCTSINGLES, regression_data$MEDHVAL)

mean_medhval <- mean(regression_data$MEDHVAL)
mean_pctbachmor <- mean(regression_data$PCTBACHMOR)
mean_nbelpov100 <- mean(regression_data$NBELPOV100)
mean_pctvacant <- mean(regression_data$PCTVACANT)
mean_pctsingles <- mean(regression_data$PCTSINGLES)

sd_medhval <- sd(regression_data$MEDHVAL)
sd_pctbachmor <- sd(regression_data$PCTBACHMOR)
sd_nbelpov100 <- sd(regression_data$NBELPOV100)
sd_pctvacant <- sd(regression_data$PCTVACANT)
sd_pctsingles <- sd(regression_data$PCTSINGLES)
```

```{r exploratory-data-analysis-log}
#| echo: false
#| results: "hide" # Hide the output
#| message: false  # Hide messages
#| warning: false  # Hide warnings
#| fig.show: "hide" # Hide plots/figures
regression_data$LNMEDHVAL<-log(regression_data$MEDHVAL)

regression_data$LNPCTBACHMOR<-log(1+regression_data$PCTBACHMOR)
regression_data$LNNBELPOV100<-log(1+regression_data$NBELPOV100)
regression_data$LNPCTVACANT<-log(1+regression_data$PCTVACANT)
regression_data$LNPCTSINGLES<-log(1+regression_data$PCTSINGLES)

hist(regression_data$LNMEDHVAL)
hist(regression_data$LNPCTBACHMOR)
hist(regression_data$LNNBELPOV100)
hist(regression_data$LNPCTVACANT)
hist(regression_data$LNPCTSINGLES)

plot(regression_data$PCTBACHMOR, regression_data$LNMEDHVAL)
plot(regression_data$LNNBELPOV100, regression_data$LNMEDHVAL)
plot(regression_data$PCTVACANT, regression_data$LNMEDHVAL)
plot(regression_data$PCTSINGLES, regression_data$LNMEDHVAL)

cor(regression_data$PCTBACHMOR, regression_data$LNMEDHVAL, method="pearson")
cor(regression_data$LNNBELPOV100, regression_data$LNMEDHVAL, method="pearson")
cor(regression_data$PCTVACANT, regression_data$LNMEDHVAL, method="pearson")
cor(regression_data$PCTSINGLES, regression_data$LNMEDHVAL, method="pearson")

trimmed_regression_data <- regression_data %>% dplyr::select(PCTBACHMOR, LNNBELPOV100, PCTVACANT, LNMEDHVAL, PCTSINGLES)
#remove LNMEDHVAL in final product
cor(trimmed_regression_data)
```

```{r exploratory-data-analysis-mapping}
#| echo: false
#| results: "hide" # Hide the output
#| message: false  # Hide messages
#| warning: false  # Hide warnings
#| fig.show: "hide" # Hide plots/figures
Regression_shpData <- st_read("./Lecture 1 - RegressionData.shp")

ggplot(Regression_shpData) +
  geom_sf(aes(fill =  LNMEDHVAL), color = NA) +
  scale_fill_viridis_c(option = "plasma")+
  labs(
    title = "Log Transformed Median House Value by Census Block Groups",
    subtitle = "Philadelphia"
  ) +
  theme_minimal()

base_theme <- theme_minimal() +
  theme(
    axis.text = element_blank(),
    axis.title = element_blank(),
    panel.grid = element_blank(),
    plot.title = element_text(size = 6, margin = margin(b = 4))  # smaller + some breathing room
  )

p1 <- ggplot(Regression_shpData) +
  geom_sf(aes(fill = PCTVACANT), color = NA) +
  scale_fill_viridis_c(option = "plasma", na.value = "grey80") +
  labs(title = "Percent of Housing Units that are Vacant,\n at Block Group", fill = "Value") +
  theme_minimal() +
  theme(axis.text = element_blank(), axis.title = element_blank(), panel.grid = element_blank()) +
  base_theme

p2 <- ggplot(Regression_shpData) +
  geom_sf(aes(fill = PCTSINGLES), color = NA) +
  scale_fill_viridis_c(option = "plasma", na.value = "grey80") +
  labs(title = "Percent of Housing Units that are Single Family Detatched,\n at Block Group", fill = "Value") +
  theme_minimal() +
  theme(axis.text = element_blank(), axis.title = element_blank(), panel.grid = element_blank()) +
  base_theme

p3 <- ggplot(Regression_shpData) +
  geom_sf(aes(fill = PCTBACHMOR), color = NA) +
  scale_fill_viridis_c(option = "plasma", na.value = "grey80") +
  labs(title = "Percent of Housing Units that have at least Bachelor's Degree,\n at Block Group", fill = "Value") +
  theme_minimal() +
  theme(axis.text = element_blank(), axis.title = element_blank(), panel.grid = element_blank()) +
  base_theme

p4 <- ggplot(Regression_shpData) +
  geom_sf(aes(fill = LNNBELPOV), color = NA) +
  scale_fill_viridis_c(option = "plasma", na.value = "grey80") +
  labs(title = "Log Transformed Number of Households Below 100% Poverty Level,\n at Block Group", fill = "Value") +
  theme_minimal() +
  theme(axis.text = element_blank(), axis.title = element_blank(), panel.grid = element_blank()) +
  base_theme

(p1 | p2) / (p3 | p4)
```

```{r multiple-regression-analysis}
#| echo: false
#| results: "hide" # Hide the output
#| message: false  # Hide messages
#| warning: false  # Hide warnings
#| fig.show: "hide" # Hide plots/figures
reg1 <- lm(LNMEDHVAL ~ PCTVACANT + PCTSINGLES + PCTBACHMOR + LNNBELPOV, data=Regression_shpData)

summary(reg1)

anova(reg1)

Regression_shpData$predvals <- fitted(reg1) 

Regression_shpData$resids <- residuals(reg1)

Regression_shpData$stdres <- rstandard(reg1)

plot(Regression_shpData$predvals, Regression_shpData$stdres)

```

```{r step}
#| echo: false
#| results: "hide" # Hide the output
#| message: false  # Hide messages
#| warning: false  # Hide warnings
#| fig.show: "hide" # Hide plots/figures
step <- stepAIC(reg1, direction="both")

step$anova
```

```{r k-fold-cv}
#| echo: false
#| results: "hide" # Hide the output
#| message: false  # Hide messages
#| warning: false  # Hide warnings
#| fig.show: "hide" # Hide plots/figures
train_control <- trainControl(method = "cv", number = 5)

cv_model <- train(LNMEDHVAL ~ PCTVACANT + PCTSINGLES + PCTBACHMOR + LNNBELPOV,
                  data = Regression_shpData,
                  method = "lm",
                  trControl = train_control)
cv_model

cv_model_2 <- train(LNMEDHVAL ~ PCTVACANT + MEDHHINC,
                  data = Regression_shpData,
                  method = "lm",
                  trControl = train_control)
cv_model_2
```

```{r std-residuals-charts}
#| echo: false
#| results: "hide" # Hide the output
#| message: false  # Hide messages
#| warning: false  # Hide warnings
#| fig.show: "hide" # Hide plots/figures
hist(Regression_shpData$stdres)

ggplot(Regression_shpData) +
  geom_sf(aes(fill =  stdres), color = NA) +
  scale_fill_viridis_c(option = "plasma")+
  labs(
    title = "",
    subtitle = ""
  ) +
  theme_minimal()
```

# Introduction

# Methods

## Data Cleaning

## Exploratory Data Analysis

## Multiple Regression Analysis

## Additional Analysis

## Software Used

# Results

## Exploratory Results

## Regression Results

## Regression Assumption Checks

## Additional Models

# Discussion & Limitations

